# Generated by Django 6.1 on 2026-09-02 06:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#0d6efd', help_text="Couleur (hex) utilisée pour repérer ce type de produit dans l'interface.", max_length=7)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie / type de produit',
                'verbose_name_plural': 'Catégories / types de produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence (SKU)')),
                ('unite', models.CharField(default='pièce', help_text='Ex: pièce, carton, litre, kg', max_length=20)),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=5, help_text='En dessous de ce seuil, le produit est en alerte.')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True, help_text='Décochez pour désactiver sans supprimer.')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='stock.categorie')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.produit')),
            ],
            options={
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
