# Generated by Django 6.1.1 on 2026-09-04 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('promotion', models.PositiveSmallIntegerField(help_text="Année d'entrée, ex: 2024")),
                ('est_actif', models.BooleanField(default=True, help_text='Décochez pour désactiver sans supprimer (ex: abandon).')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='academique.filiere')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_etudiant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='academique.anneeacademique')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academique.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='etudiants.etudiant')),
            ],
            options={
                'ordering': ['-date_inscription'],
                'unique_together': {('etudiant', 'cours', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Note sur 20.', max_digits=4)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='academique.anneeacademique')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academique.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='etudiants.etudiant')),
                ('evaluee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_evaluation'],
                'unique_together': {('etudiant', 'cours', 'annee_academique')},
            },
        ),
    ]
