# Generated by Django 6.1.1 on 2026-09-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex: 2025-2026', max_length=20, unique=True)),
                ('est_courante', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-libelle'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('credits', models.PositiveSmallIntegerField(default=3)),
                ('capacite_max', models.PositiveIntegerField(default=60)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('couleur', models.CharField(default='#0d6efd', help_text="Couleur d'identification dans l'interface.", max_length=7)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('duree_annees', models.PositiveSmallIntegerField(default=3)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
