# Generated by Django 6.1.1 on 2026-09-04 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='professeurs',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'PROFESSEUR'}, related_name='cours_enseignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cours',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academique.departement'),
        ),
        migrations.AddField(
            model_name='departement',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='academique.faculte'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='academique.departement'),
        ),
        migrations.AlterUniqueTogether(
            name='departement',
            unique_together={('faculte', 'nom')},
        ),
    ]
